from settings import URL, TYPE_FEED
from functions import get_feeds, get_cookie, get_date_with_offset

if __name__ == '__main__':
    cookie = get_cookie()
    end_date = get_date_with_offset(
        int(input('Введите период для проверки: ')))
    get_feeds(URL, type_feed=TYPE_FEED, cookie=cookie, date_end_check=end_date)

x = {'date': '2023-08-30T10:10:35.000+0300',
     'data': {'fknumber': '32224010230284199009', 'attachCnt': 3,
              'unreadThread': 0, 'hasRegLetter': True,
              'deptMessageType': 'INFO', 'messageCnt': 3, 'handed': True},
     'unread': False, 'hasQuiz': False, 'mobileTitle': 'ФССП России',
     'archive': False, 'chiefOnly': False, 'title': 'ФССП России',
     'ownerId': 242226241, 'userId': 242226241,
     'subTitle': 'Постановление судебного пристава об окончании исполнительного  производства',
     'hiddenEvents': False, 'feedType': 'GEPS', 'id': 114957596603,
     'extId': '8511630670',
     'detail': {'updateDate': None, 'messageCount': None, 'hidden': False,
                'sendDate': '22.08.2023 06:03', 'subject': None,
                'originator': 'FSSP01', 'threadId': 8511630670,
                'archived': False, 'toName': 'Климов Артём Владимирович',
                'fromName': 'ФЕДЕРАЛЬНАЯ СЛУЖБА СУДЕБНЫХ ПРИСТАВОВ',
                'additionalData': None, 'hasAttachments': None,
                'sendDateMilliseconds': 1692673418000,
                'statusMnemonic': 'DELIVERED', 'read': True, 'iconName': None,
                'addParams': {'DSideTypeType': '2',
                              'IdDocType_text': 'постановление о запрете на регистрационные действия в отношении транспортных средств',
                              'IDocSubjExecName': 'Задолженность по платежам за газ, тепло и электроэнергию',
                              'fknumberHash': 'KkIYasNqtQyjReoZEYVyRg',
                              'feed_mobtitle': 'ФССП России',
                              'NumberDoc': '24010/23/1027197',
                              'IdDocType_feed': 'Постановление о запрете на регистрационные действия в отношении транспортных средств',
                              'RiseDate': '21.08.2023',
                              'DocRegDate': '2023-08-22 04:25:47',
                              'CrdrName': 'ПАО "Красноярскэнергосбыт"',
                              'IdDoc': '4103567210086',
                              'feed_title': 'ФССП России',
                              'IDNum': '2-1825/58/2023',
                              'IdDocType_push': 'Постановление о запрете на регистрационные действия в отношении транспортных средств',
                              'inner_mobtitle': 'ФССП России',
                              'SupplierOrgName': 'Отделение судебных приставов по Ленинскому району г. Красноярска',
                              'IdDocType_Picture': 'https://gu-st.ru/content/mail/fssp/banner_door_bell2.png',
                              'feed_subtitle': 'Постановление о запрете на регистрационные действия в отношении транспортных средств',
                              'DebtSumTotal': '1534.34',
                              'DbtrName': 'Климов Артём Владимирович',
                              'IDDate': '11.05.2023',
                              'IDOrganName': 'Судебный участок N 58 в Ленинском районе г. Красноярска',
                              'PostName': 'Судебный пристав-исполнитель',
                              'IDTypeCode': '4',
                              'IpInternalKey': '4103566345741',
                              'DeloNum': '284199/23/24010-ИП',
                              'SubjNum_text': 'неоплаченные счета за газ, тепло и электроэнергию',
                              'DocName': 'Постановление о запрете на регистрационные действия в отношении транспортных средств',
                              'OspCode': '24010',
                              'IdDocType': 'O_IP_ACT_BAN_GIBDD',
                              'SPIShortName': 'Дудко Марина Валерьевна',
                              'DateDoc': '22.08.2023',
                              'IDTypeCode_text': 'судебным приказом',
                              'SPITelephone': '+7(391)246-06-64',
                              'template_id': 5739,
                              'UIN': '32224010230284199009',
                              'inner_subtitle': 'Постановление о запрете на регистрационные действия в отношении транспортных средств',
                              'SubjNum': '1460000',
                              'inner_title': 'ФССП России'},
                'threadTypeName': 'Оповещение', 'updateDateMilliseconds': None,
                'firstMessageId': None, 'agencyName': None,
                'statusHistory': [
             {'createDateMilliseconds': 1692673418000, 'statusId': 105,
              'mnemonic': 'DELIVERED_TO_USER', 'messageId': 8511630670,
              'originator': 'ФССП РОССИИ', 'userName': '',
              'createDate': '2023-08-22T06:03:38.000+03:00',
              'status': 'доставлено'},
             {'createDateMilliseconds': 1692673419000, 'statusId': 308,
              'mnemonic': 'DELIVERED_TO_FEED', 'messageId': 8511630670,
              'originator': 'Служба технической поддержки', 'userName': '',
              'createDate': '2023-08-22T06:03:39.000+03:00',
              'status': 'Доставлено'},
             {'createDateMilliseconds': 1692674278000, 'statusId': 571,
              'mnemonic': 'AUTHORIZE_CONFIRMED', 'messageId': 8511630670,
              'originator': 'Климов Артём Владимирович',
              'userName': 'Климов А. В.',
              'createDate': '2023-08-22T06:17:58.000+03:00',
              'status': 'Просмотрено пользователем во время авторизации'},
             {'createDateMilliseconds': 1692674279000, 'statusId': 808,
              'mnemonic': 'HAND_TO_USER', 'messageId': 8511630670,
              'originator': 'Климов Артём Владимирович',
              'userName': 'Климов А. В.',
              'createDate': '2023-08-22T06:17:59.000+03:00',
              'status': 'Вручено пользователю'},
             {'createDateMilliseconds': 1692674279000, 'statusId': 570,
              'mnemonic': 'DELIVERY_CONFIRMED', 'messageId': 8511630670,
              'originator': 'Климов Артём Владимирович',
              'userName': 'Климов А. В.',
              'createDate': '2023-08-22T06:17:59.000+03:00',
              'status': 'Просмотрено пользователем в личном кабинете (подтверждена доставка)'},
             {'createDateMilliseconds': 1692674294000, 'statusId': 368,
              'mnemonic': 'READ_BY_USER', 'messageId': 8511630670,
              'originator': 'Климов Артём Владимирович',
              'userName': 'Климов А. В.',
              'createDate': '2023-08-22T06:18:14.000+03:00',
              'status': 'Прочитано пользователем'}], 'messages': [
             {'sourceRegistryId': None, 'sendDate': '22.08.2023 06:03',
              'targetIds': None, 'subject': 'Уведомления ФССП о ходе ИП',
              'threadTypeId': 103, 'wsTemplateCode': 'FSSP_PROGRESS_FL',
              'threadId': 8511630670, 'sourceRecordId': None,
              'toName': 'Климов Артём Владимирович', 'deadlinePercent': None,
              'fromName': 'ФССП РОССИИ', 'isActiveNotif': True,
              'text': '<div class="mail-body-content mini-bottom"><div class="lg-h-title-16-big md-h-title-16-big sm-h-title-16 text-plain"><div>Артём Владимирович</div><div class="all-offset-top-8 mt-8">Вам направлено постановление в&nbsp;рамках исполнительного производства №&nbsp;284199/23/24010-ИП от&nbsp;21.08.2023</div><div class="all-offset-top-24 mt-24" style="background-color: #EDF2FE; padding: 20px; border-radius: 8px;"><div><b>Документ:</b> Постановление о запрете на регистрационные действия в отношении транспортных средств</div><div class="all-offset-top-12 mt-12"><b>Сумма взыскания:</b> 1&nbsp;534,34&nbsp;&#8381;</div><div class="all-offset-top-12 mt-12"><b>Причина:</b> неоплаченные счета за газ, тепло и электроэнергию в&nbsp;соответствии с&nbsp;судебным приказом №&nbsp;2-1825/58/2023 от 11.05.2023</div><div class="all-offset-top-12 mt-12"><b>Отдел ФССП:</b> Отделение судебных приставов по Ленинскому району г. Красноярска, код отдела 24010</div><div class="all-offset-top-12 mt-12"><b>Судебный пристав:</b> Дудко Марина Валерьевна, +7(391)246-06-64</div></div><div class="all-offset-top-24 mt-24">Что&nbsp;можно сделать:</div><ul class="all-offset-top-8 mt-8 list-dashed"><li><a href="https://www.gosuslugi.ru/600352/1/form?external=&screenId=sInformerLink&ipnum=284199/23/24010-ИП&ctype=Должник" target="_blank">узнать о&nbsp;ходе</a> исполнительного производства</li><li class="all-offset-top-12 mt-12"><a href="https://www.gosuslugi.ru/600367/1/form?external&screenId=extSource&ipnum=284199/23/24010-ИП&ctype=Должник" target="_blank">обратиться в&nbsp;ФССП</a> с&nbsp;заявлением, жалобой или&nbsp;дополнительной информацией по&nbsp;вашему делу</li></ul></div></div>',
              'isLegal': True, 'deadlineDate': None,
              'updateDateMilliseconds': 1692673418000, 'messageId': 8511630670,
              'signed': False, 'eventType': 'FSSP_PROGRESS_FL',
              'eventInfo': None, 'createDateMilliseconds': 1692673418000,
              'sourceType': None, 'threadType': 'INFO', 'opponentName': None,
              'isReply': None, 'hash': None, 'toId': 9432343,
              'opponentId': None, 'updateDate': '22.08.2023 06:03',
              'attachments': [
                  {'fileName': 'piev_4103567210123.xml', 'fileSize': 11415,
                   'eds': 'OK', 'messageId': 8511630670, 'signed': True,
                   'attachmentId': 6509920253, 'mimeType': 'application/xml',
                   'parentId': 6509920251, 'status': 'READY'},
                  {'fileName': 'piev_4103567210123.pdf', 'fileSize': 87635,
                   'messageId': 8511630670, 'signed': False,
                   'attachmentId': 6509920254, 'mimeType': 'application/pdf',
                   'parentId': 6509920251, 'status': 'READY'}],
              'hidden': False, 'isRead': True, 'fromOid': 1000295184,
              'isDeleted': None, 'sourceMsgId': None, 'opponentOrgId': None,
              'textProviderId': 2, 'createDate': '22.08.2023 06:03',
              'sendDateMilliseconds': 1692673418000,
              'addParams': {'DSideTypeType': '2',
                            'IdDocType_text': 'постановление о запрете на регистрационные действия в отношении транспортных средств',
                            'IDocSubjExecName': 'Задолженность по платежам за газ, тепло и электроэнергию',
                            'fknumberHash': 'KkIYasNqtQyjReoZEYVyRg',
                            'feed_mobtitle': 'ФССП России',
                            'NumberDoc': '24010/23/1027197',
                            'IdDocType_feed': 'Постановление о запрете на регистрационные действия в отношении транспортных средств',
                            'RiseDate': '21.08.2023',
                            'DocRegDate': '2023-08-22 04:25:47',
                            'CrdrName': 'ПАО "Красноярскэнергосбыт"',
                            'IdDoc': '4103567210086',
                            'feed_title': 'ФССП России',
                            'IDNum': '2-1825/58/2023',
                            'IdDocType_push': 'Постановление о запрете на регистрационные действия в отношении транспортных средств',
                            'inner_mobtitle': 'ФССП России',
                            'SupplierOrgName': 'Отделение судебных приставов по Ленинскому району г. Красноярска',
                            'IdDocType_Picture': 'https://gu-st.ru/content/mail/fssp/banner_door_bell2.png',
                            'feed_subtitle': 'Постановление о запрете на регистрационные действия в отношении транспортных средств',
                            'DebtSumTotal': '1534.34',
                            'DbtrName': 'Климов Артём Владимирович',
                            'IDDate': '11.05.2023',
                            'IDOrganName': 'Судебный участок N 58 в Ленинском районе г. Красноярска',
                            'PostName': 'Судебный пристав-исполнитель',
                            'IDTypeCode': '4',
                            'IpInternalKey': '4103566345741',
                            'DeloNum': '284199/23/24010-ИП',
                            'SubjNum_text': 'неоплаченные счета за газ, тепло и электроэнергию',
                            'DocName': 'Постановление о запрете на регистрационные действия в отношении транспортных средств',
                            'OspCode': '24010',
                            'IdDocType': 'O_IP_ACT_BAN_GIBDD',
                            'SPIShortName': 'Дудко Марина Валерьевна',
                            'DateDoc': '22.08.2023',
                            'IDTypeCode_text': 'судебным приказом',
                            'SPITelephone': '+7(391)246-06-64',
                            'template_id': 5739, 'UIN': '32224010230284199009',
                            'inner_subtitle': 'Постановление о запрете на регистрационные действия в отношении транспортных средств',
                            'SubjNum': '1460000',
                            'inner_title': 'ФССП России'},
              'wsTemplateId': 5739, 'categoryCode': None, 'fromId': 114323832,
              'userId': None, 'hasLegal': None, 'directionCode': 'in',
              'sourceTypeId': 448, 'statusHistory': [
                 {'createDateMilliseconds': 1692673418000, 'statusId': 105,
                  'mnemonic': 'DELIVERED_TO_USER', 'messageId': 8511630670,
                  'originator': 'ФССП РОССИИ', 'userName': '',
                  'createDate': '2023-08-22T06:03:38.000+03:00',
                  'status': 'доставлено'},
                 {'createDateMilliseconds': 1692673419000, 'statusId': 308,
                  'mnemonic': 'DELIVERED_TO_FEED', 'messageId': 8511630670,
                  'originator': 'Служба технической поддержки', 'userName': '',
                  'createDate': '2023-08-22T06:03:39.000+03:00',
                  'status': 'Доставлено'},
                 {'createDateMilliseconds': 1692674278000, 'statusId': 571,
                  'mnemonic': 'AUTHORIZE_CONFIRMED', 'messageId': 8511630670,
                  'originator': 'Климов Артём Владимирович',
                  'userName': 'Климов А. В.',
                  'createDate': '2023-08-22T06:17:58.000+03:00',
                  'status': 'Просмотрено пользователем во время авторизации'},
                 {'createDateMilliseconds': 1692674279000, 'statusId': 808,
                  'mnemonic': 'HAND_TO_USER', 'messageId': 8511630670,
                  'originator': 'Климов Артём Владимирович',
                  'userName': 'Климов А. В.',
                  'createDate': '2023-08-22T06:17:59.000+03:00',
                  'status': 'Вручено пользователю'},
                 {'createDateMilliseconds': 1692674279000, 'statusId': 570,
                  'mnemonic': 'DELIVERY_CONFIRMED', 'messageId': 8511630670,
                  'originator': 'Климов Артём Владимирович',
                  'userName': 'Климов А. В.',
                  'createDate': '2023-08-22T06:17:59.000+03:00',
                  'status': 'Просмотрено пользователем в личном кабинете (подтверждена доставка)'},
                 {'createDateMilliseconds': 1692674294000, 'statusId': 368,
                  'mnemonic': 'READ_BY_USER', 'messageId': 8511630670,
                  'originator': 'Климов Артём Владимирович',
                  'userName': 'Климов А. В.',
                  'createDate': '2023-08-22T06:18:14.000+03:00',
                  'status': 'Прочитано пользователем'}], 'fromOrgId': 617526,
              'assignedUserName': None, 'attachmentCount': None,
              'assignedUserId': None},
             {'sourceRegistryId': None, 'sendDate': '24.08.2023 18:23',
              'targetIds': None, 'subject': 'Уведомления ФССП о ходе ИП',
              'threadTypeId': 103, 'wsTemplateCode': 'FSSP_PROGRESS_FL',
              'threadId': 8511630670, 'sourceRecordId': None,
              'toName': 'Климов Артём Владимирович', 'deadlinePercent': None,
              'fromName': 'ФССП РОССИИ', 'isActiveNotif': True,
              'text': '<div class="mail-body-content mini-bottom"><div class="lg-h-title-16-big md-h-title-16-big sm-h-title-16 text-plain"><div>Артём Владимирович</div><div class="all-offset-top-8 mt-8">Вам направлено постановление в&nbsp;рамках исполнительного производства №&nbsp;284199/23/24010-ИП от&nbsp;21.08.2023</div><div class="all-offset-top-24 mt-24" style="background-color: #EDF2FE; padding: 20px; border-radius: 8px;"><div><b>Документ:</b> Постановление об отмене запрета на регистрационные действия в отношении транспортных средств</div><div class="all-offset-top-12 mt-12"><b>Причина:</b> неоплаченные счета за газ, тепло и электроэнергию в&nbsp;соответствии с&nbsp;судебным приказом №&nbsp;2-1825/58/2023 от 11.05.2023</div><div class="all-offset-top-12 mt-12"><b>Отдел ФССП:</b> Отделение судебных приставов по Ленинскому району г. Красноярска, код отдела 24010</div><div class="all-offset-top-12 mt-12"><b>Судебный пристав:</b> Дудко Марина Валерьевна, +7(391)246-06-64</div></div><div class="all-offset-top-24 mt-24">Что&nbsp;можно сделать:</div><ul class="all-offset-top-8 mt-8 list-dashed"><li><a href="https://www.gosuslugi.ru/600352/1/form?external=&screenId=sInformerLink&ipnum=284199/23/24010-ИП&ctype=Должник" target="_blank">узнать о&nbsp;ходе</a> исполнительного производства</li><li class="all-offset-top-12 mt-12"><a href="https://www.gosuslugi.ru/600367/1/form?external&screenId=extSource&ipnum=284199/23/24010-ИП&ctype=Должник" target="_blank">обратиться в&nbsp;ФССП</a> с&nbsp;заявлением, жалобой или&nbsp;дополнительной информацией по&nbsp;вашему делу</li></ul></div></div>',
              'isLegal': True, 'deadlineDate': None,
              'updateDateMilliseconds': 1692890608000, 'messageId': 8537753691,
              'signed': False, 'eventType': 'FSSP_PROGRESS_FL',
              'eventInfo': None, 'createDateMilliseconds': 1692890608000,
              'sourceType': None, 'threadType': 'INFO', 'opponentName': None,
              'isReply': None, 'hash': None, 'toId': 9432343,
              'opponentId': None, 'updateDate': '24.08.2023 18:23',
              'attachments': [
                  {'fileName': 'piev_4103568250787.xml', 'fileSize': 10330,
                   'eds': 'OK', 'messageId': 8537753691, 'signed': True,
                   'attachmentId': 6543930566, 'mimeType': 'application/xml',
                   'parentId': 6543930560, 'status': 'READY'},
                  {'fileName': 'piev_4103568250787.pdf', 'fileSize': 115455,
                   'messageId': 8537753691, 'signed': False,
                   'attachmentId': 6543930567, 'mimeType': 'application/pdf',
                   'parentId': 6543930560, 'status': 'READY'}],
              'hidden': False, 'isRead': True, 'fromOid': 1000295184,
              'isDeleted': None, 'sourceMsgId': None, 'opponentOrgId': None,
              'textProviderId': 2, 'createDate': '24.08.2023 18:23',
              'sendDateMilliseconds': 1692890608000,
              'addParams': {'DSideTypeType': '2',
                            'IdDocType_text': 'постановление об отмене запрета на регистрационные действия в отношении транспортных средств',
                            'IDocSubjExecName': 'Задолженность по платежам за газ, тепло и электроэнергию',
                            'fknumberHash': 'KkIYasNqtQyjReoZEYVyRg',
                            'feed_mobtitle': 'ФССП России',
                            'NumberDoc': '24010/23/1042470',
                            'IdDocType_feed': 'Постановление об отмене запрета на регистрационные действия в отношении транспортных средств',
                            'RiseDate': '21.08.2023',
                            'DocRegDate': '2023-08-24 16:48:46',
                            'CrdrName': 'ПАО "Красноярскэнергосбыт"',
                            'IdDoc': '4103568250572',
                            'feed_title': 'ФССП России',
                            'IDNum': '2-1825/58/2023',
                            'IdDocType_push': 'Постановление об отмене запрета на регистрационные действия в отношении транспортных средств',
                            'inner_mobtitle': 'ФССП России',
                            'SupplierOrgName': 'Отделение судебных приставов по Ленинскому району г. Красноярска',
                            'IdDocType_Picture': 'https://gu-st.ru/content/mail/fssp/banner_door_bell2.png',
                            'feed_subtitle': 'Постановление об отмене запрета на регистрационные действия в отношении транспортных средств',
                            'DebtSumTotal': '0.00',
                            'DbtrName': 'Климов Артём Владимирович',
                            'IDDate': '11.05.2023',
                            'IDOrganName': 'Судебный участок N 58 в Ленинском районе г. Красноярска',
                            'PostName': 'Судебный пристав-исполнитель',
                            'IDTypeCode': '4',
                            'IpInternalKey': '4103566345741',
                            'DeloNum': '284199/23/24010-ИП',
                            'SubjNum_text': 'неоплаченные счета за газ, тепло и электроэнергию',
                            'DocName': 'Постановление об отмене запрета на регистрационные действия в отношении транспортных средств',
                            'OspCode': '24010',
                            'IdDocType': 'O_IP_ACT_ENDBAN_GIBDD',
                            'SPIShortName': 'Дудко Марина Валерьевна',
                            'DateDoc': '24.08.2023',
                            'IDTypeCode_text': 'судебным приказом',
                            'SPITelephone': '+7(391)246-06-64',
                            'template_id': 5739, 'UIN': '32224010230284199009',
                            'inner_subtitle': 'Постановление об отмене запрета на регистрационные действия в отношении транспортных средств',
                            'SubjNum': '1460000',
                            'inner_title': 'ФССП России'},
              'wsTemplateId': 5739, 'categoryCode': None, 'fromId': 114323832,
              'userId': None, 'hasLegal': None, 'directionCode': 'in',
              'sourceTypeId': 448, 'statusHistory': [
                 {'createDateMilliseconds': 1692890608000, 'statusId': 105,
                  'mnemonic': 'DELIVERED_TO_USER', 'messageId': 8537753691,
                  'originator': 'ФССП РОССИИ', 'userName': '',
                  'createDate': '2023-08-24T18:23:28.000+03:00',
                  'status': 'доставлено'},
                 {'createDateMilliseconds': 1692890613000, 'statusId': 308,
                  'mnemonic': 'DELIVERED_TO_FEED', 'messageId': 8537753691,
                  'originator': 'Служба технической поддержки', 'userName': '',
                  'createDate': '2023-08-24T18:23:33.000+03:00',
                  'status': 'Доставлено'},
                 {'createDateMilliseconds': 1693323219000, 'statusId': 571,
                  'mnemonic': 'AUTHORIZE_CONFIRMED', 'messageId': 8537753691,
                  'originator': 'Климов Артём Владимирович',
                  'userName': 'Климов А. В.',
                  'createDate': '2023-08-29T18:33:39.000+03:00',
                  'status': 'Просмотрено пользователем во время авторизации'},
                 {'createDateMilliseconds': 1693323219000, 'statusId': 808,
                  'mnemonic': 'HAND_TO_USER', 'messageId': 8537753691,
                  'originator': 'Климов Артём Владимирович',
                  'userName': 'Климов А. В.',
                  'createDate': '2023-08-29T18:33:39.000+03:00',
                  'status': 'Вручено пользователю'},
                 {'createDateMilliseconds': 1693323229000, 'statusId': 570,
                  'mnemonic': 'DELIVERY_CONFIRMED', 'messageId': 8537753691,
                  'originator': 'Климов Артём Владимирович',
                  'userName': 'Климов А. В.',
                  'createDate': '2023-08-29T18:33:49.000+03:00',
                  'status': 'Просмотрено пользователем в личном кабинете (подтверждена доставка)'},
                 {'createDateMilliseconds': 1693816448000, 'statusId': 368,
                  'mnemonic': 'READ_BY_USER', 'messageId': 8537753691,
                  'originator': 'Климов Артём Владимирович',
                  'userName': 'Климов А. В.',
                  'createDate': '2023-09-04T11:34:08.000+03:00',
                  'status': 'Прочитано пользователем'}], 'fromOrgId': 617526,
              'assignedUserName': None, 'attachmentCount': None,
              'assignedUserId': None},
             {'sourceRegistryId': None, 'sendDate': '30.08.2023 10:10',
              'targetIds': None, 'subject': 'Уведомления ФССП о ходе ИП',
              'threadTypeId': 103, 'wsTemplateCode': 'FSSP_PROGRESS_FL',
              'threadId': 8511630670, 'sourceRecordId': None,
              'toName': 'Климов Артём Владимирович', 'deadlinePercent': None,
              'fromName': 'ФССП РОССИИ', 'isActiveNotif': True,
              'text': '<div class="mail-body-content mini-bottom"><div class="lg-h-title-16-big md-h-title-16-big sm-h-title-16 text-plain"><div>Артём Владимирович</div><div class="all-offset-top-8 mt-8">Вам направлено постановление в&nbsp;рамках исполнительного производства №&nbsp;284199/23/24010-ИП от&nbsp;21.08.2023</div><div class="all-offset-top-24 mt-24" style="background-color: #EDF2FE; padding: 20px; border-radius: 8px;"><div><b>Документ:</b> Постановление об окончании исполнительного производства</div><div class="all-offset-top-12 mt-12"><b>Причина:</b> неоплаченные счета за газ, тепло и электроэнергию в&nbsp;соответствии с&nbsp;судебным приказом №&nbsp;2-1825/58/2023 от 11.05.2023</div><div class="all-offset-top-12 mt-12"><b>Отдел ФССП:</b> Отделение судебных приставов по Ленинскому району г. Красноярска, код отдела 24010</div><div class="all-offset-top-12 mt-12"><b>Судебный пристав:</b> Дудко Марина Валерьевна, +7(391)246-06-64</div></div><div class="all-offset-top-24 mt-24">Что&nbsp;можно сделать:</div><ul class="all-offset-top-8 mt-8 list-dashed"><li><a href="https://www.gosuslugi.ru/600352/1/form?external=&screenId=sInformerLink&ipnum=284199/23/24010-ИП&ctype=Должник" target="_blank">узнать о&nbsp;ходе</a> исполнительного производства</li><li class="all-offset-top-12 mt-12"><a href="https://www.gosuslugi.ru/600367/1/form?external&screenId=extSource&ipnum=284199/23/24010-ИП&ctype=Должник" target="_blank">обратиться в&nbsp;ФССП</a> с&nbsp;заявлением, жалобой или&nbsp;дополнительной информацией по&nbsp;вашему делу</li></ul></div></div>',
              'isLegal': True, 'deadlineDate': None,
              'updateDateMilliseconds': 1693379435000, 'messageId': 8575789220,
              'signed': False, 'eventType': 'FSSP_PROGRESS_FL',
              'eventInfo': None, 'createDateMilliseconds': 1693379435000,
              'sourceType': None, 'threadType': 'INFO', 'opponentName': None,
              'isReply': None, 'hash': None, 'toId': 9432343,
              'opponentId': None, 'updateDate': '30.08.2023 10:10',
              'attachments': [
                  {'fileName': 'piev_4103569599787.pdf', 'fileSize': 82434,
                   'messageId': 8575789220, 'signed': False,
                   'attachmentId': 6589552630, 'mimeType': 'application/pdf',
                   'parentId': 6589552629, 'status': 'READY'},
                  {'fileName': 'piev_4103569599787.xml', 'fileSize': 7237,
                   'eds': 'OK', 'messageId': 8575789220, 'signed': True,
                   'attachmentId': 6589552631, 'mimeType': 'application/xml',
                   'parentId': 6589552629, 'status': 'READY'}],
              'hidden': False, 'isRead': True, 'fromOid': 1000295184,
              'isDeleted': None, 'sourceMsgId': None, 'opponentOrgId': None,
              'textProviderId': 2, 'createDate': '30.08.2023 10:10',
              'sendDateMilliseconds': 1693379435000,
              'addParams': {'DSideTypeType': '2',
                            'IdDocType_text': 'постановление судебного пристава об окончании исполнительного  производства',
                            'IDocSubjExecName': 'Задолженность по платежам за газ, тепло и электроэнергию',
                            'fknumberHash': 'KkIYasNqtQyjReoZEYVyRg',
                            'feed_mobtitle': 'ФССП России',
                            'NumberDoc': '24010/23/1062962',
                            'IdDocType_feed': 'Постановление судебного пристава об окончании исполнительного  производства',
                            'RiseDate': '21.08.2023',
                            'DocRegDate': '2023-08-30 06:42:16',
                            'CrdrName': 'ПАО "Красноярскэнергосбыт"',
                            'IdDoc': '4103569599642',
                            'feed_title': 'ФССП России',
                            'IDNum': '2-1825/58/2023',
                            'IdDocType_push': 'Постановление судебного пристава об окончании исполнительного  производства',
                            'inner_mobtitle': 'ФССП России',
                            'SupplierOrgName': 'Отделение судебных приставов по Ленинскому району г. Красноярска',
                            'IdDocType_Picture': 'https://gu-st.ru/content/mail/fssp/banner_door_bell2.png',
                            'feed_subtitle': 'Постановление судебного пристава об окончании исполнительного  производства',
                            'DebtSumTotal': '0.00',
                            'DbtrName': 'Климов Артём Владимирович',
                            'IDDate': '11.05.2023',
                            'IDOrganName': 'Судебный участок N 58 в Ленинском районе г. Красноярска',
                            'PostName': 'Судебный пристав-исполнитель',
                            'IDTypeCode': '4',
                            'IpInternalKey': '4103566345741',
                            'DeloNum': '284199/23/24010-ИП',
                            'SubjNum_text': 'неоплаченные счета за газ, тепло и электроэнергию',
                            'DocName': 'Постановление об окончании исполнительного производства',
                            'OspCode': '24010',
                            'IdDocType': 'O_IP_ACT_END_END',
                            'SPIShortName': 'Дудко Марина Валерьевна',
                            'DateDoc': '30.08.2023',
                            'IDTypeCode_text': 'судебным приказом',
                            'SPITelephone': '+7(391)246-06-64',
                            'template_id': 5739, 'UIN': '32224010230284199009',
                            'inner_subtitle': 'Постановление судебного пристава об окончании исполнительного  производства',
                            'SubjNum': '1460000',
                            'inner_title': 'ФССП России'},
              'wsTemplateId': 5739, 'categoryCode': None, 'fromId': 114323832,
              'userId': None, 'hasLegal': None, 'directionCode': 'in',
              'sourceTypeId': 448, 'statusHistory': [
                 {'createDateMilliseconds': 1693379435000, 'statusId': 105,
                  'mnemonic': 'DELIVERED_TO_USER', 'messageId': 8575789220,
                  'originator': 'ФССП РОССИИ', 'userName': '',
                  'createDate': '2023-08-30T10:10:35.000+03:00',
                  'status': 'доставлено'},
                 {'createDateMilliseconds': 1693379437000, 'statusId': 308,
                  'mnemonic': 'DELIVERED_TO_FEED', 'messageId': 8575789220,
                  'originator': 'Служба технической поддержки', 'userName': '',
                  'createDate': '2023-08-30T10:10:37.000+03:00',
                  'status': 'Доставлено'},
                 {'createDateMilliseconds': 1693816412000, 'statusId': 571,
                  'mnemonic': 'AUTHORIZE_CONFIRMED', 'messageId': 8575789220,
                  'originator': 'Климов Артём Владимирович',
                  'userName': 'Климов А. В.',
                  'createDate': '2023-09-04T11:33:32.000+03:00',
                  'status': 'Просмотрено пользователем во время авторизации'},
                 {'createDateMilliseconds': 1693816413000, 'statusId': 808,
                  'mnemonic': 'HAND_TO_USER', 'messageId': 8575789220,
                  'originator': 'Климов Артём Владимирович',
                  'userName': 'Климов А. В.',
                  'createDate': '2023-09-04T11:33:33.000+03:00',
                  'status': 'Вручено пользователю'},
                 {'createDateMilliseconds': 1693816417000, 'statusId': 570,
                  'mnemonic': 'DELIVERY_CONFIRMED', 'messageId': 8575789220,
                  'originator': 'Климов Артём Владимирович',
                  'userName': 'Климов А. В.',
                  'createDate': '2023-09-04T11:33:37.000+03:00',
                  'status': 'Просмотрено пользователем в личном кабинете (подтверждена доставка)'},
                 {'createDateMilliseconds': 1693816448000, 'statusId': 368,
                  'mnemonic': 'READ_BY_USER', 'messageId': 8575789220,
                  'originator': 'Климов Артём Владимирович',
                  'userName': 'Климов А. В.',
                  'createDate': '2023-09-04T11:34:08.000+03:00',
                  'status': 'Прочитано пользователем'}], 'fromOrgId': 617526,
              'assignedUserName': None, 'attachmentCount': None,
              'assignedUserId': None}], 'threadType': 103,
                'baseMessageId': None, 'status': 'Доставлено'},
     'status': 'inbox'}
